fid = fopen('0_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N0 = cell2mat(C);
fid = fopen('1_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N1 = cell2mat(C);
fid = fopen('2_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N2 = cell2mat(C);
fid = fopen('3_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N3 = cell2mat(C);
fid = fopen('4_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N4 = cell2mat(C);
fid = fopen('5_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N5 = cell2mat(C);
fid = fopen('6_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N6 = cell2mat(C);
fid = fopen('7_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N7 = cell2mat(C);
fid = fopen('8_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N8 = cell2mat(C);
fid = fopen('9_train.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N9 = cell2mat(C);
N = [N0;N1;N2;N3;N4;N5;N6;N7;N8;N9];
Phi_Train = [ones(size(N,1),1) N];
W = rand(513,10);
Phi_Train = double(Phi_Train);
Activation_Train = Phi_Train*W;
T0 = [ones(size(N0,1),1) zeros(size(N0,1),9)];
T1 = [zeros(size(N1,1),1) ones(size(N1,1),1) zeros(size(N1,1),8)];
T2 = [zeros(size(N2,1),2) ones(size(N2,1),1) zeros(size(N2,1),7)];
T3 = [zeros(size(N3,1),3) ones(size(N3,1),1) zeros(size(N3,1),6)];
T4 = [zeros(size(N4,1),4) ones(size(N4,1),1) zeros(size(N4,1),5)];
T5 = [zeros(size(N5,1),5) ones(size(N5,1),1) zeros(size(N5,1),4)];
T6 = [zeros(size(N6,1),6) ones(size(N6,1),1) zeros(size(N6,1),3)];
T7 = [zeros(size(N7,1),7) ones(size(N7,1),1) zeros(size(N7,1),2)];
T8 = [zeros(size(N8,1),8) ones(size(N8,1),1) zeros(size(N8,1),1)];
T9 = [zeros(size(N9,1),9) ones(size(N9,1),1)];
Target_Train = [T0;T1;T2;T3;T4;T5;T6;T7;T8;T9];

fid = fopen('0_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N0 = cell2mat(C);
fid = fopen('1_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N1 = cell2mat(C);
fid = fopen('2_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N2 = cell2mat(C);
fid = fopen('3_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N3 = cell2mat(C);
fid = fopen('4_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N4 = cell2mat(C);
fid = fopen('5_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N5 = cell2mat(C);
fid = fopen('6_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N6 = cell2mat(C);
fid = fopen('7_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N7 = cell2mat(C);
fid = fopen('8_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N8 = cell2mat(C);
fid = fopen('9_test.txt');
fmt=[repmat('%d',1,512) '%*[^\n]'];
C = (textscan(fid,fmt));     
fclose(fid);
N9 = cell2mat(C);
N = [N0;N1;N2;N3;N4;N5;N6;N7;N8;N9];
Phi_Test = [ones(size(N,1),1) N];
Phi_Test = double(Phi_Test);
T0 = [ones(size(N0,1),1) zeros(size(N0,1),9)];
T1 = [zeros(size(N1,1),1) ones(size(N1,1),1) zeros(size(N1,1),8)];
T2 = [zeros(size(N2,1),2) ones(size(N2,1),1) zeros(size(N2,1),7)];
T3 = [zeros(size(N3,1),3) ones(size(N3,1),1) zeros(size(N3,1),6)];
T4 = [zeros(size(N4,1),4) ones(size(N4,1),1) zeros(size(N4,1),5)];
T5 = [zeros(size(N5,1),5) ones(size(N5,1),1) zeros(size(N5,1),4)];
T6 = [zeros(size(N6,1),6) ones(size(N6,1),1) zeros(size(N6,1),3)];
T7 = [zeros(size(N7,1),7) ones(size(N7,1),1) zeros(size(N7,1),2)];
T8 = [zeros(size(N8,1),8) ones(size(N8,1),1) zeros(size(N8,1),1)];
T9 = [zeros(size(N9,1),9) ones(size(N9,1),1)];
Target_Test = [T0;T1;T2;T3;T4;T5;T6;T7;T8;T9];

save filesplit.mat